export type TypeInstance = {
  id: string;
  name: string;
  status: boolean;
  agreement: boolean;
  agreementDate: string | null;
  paymentDay: number;
  paymentValue: number;
  paymentPlan: "standard" | "standard_ai" | "empresarial";
  paymentTier: "monthly" | "yearly";
  responsibleName: string;
  responsibleDocument1: string;
  responsibleDocument2: string;
  responsiblePhone: string;
  responsibleMobile: string;
  responsibleEmail: string;
  companyName: string;
  companyDocument: string;
  companyPhone: string;
  companyMobile: string;
  companyEmail: string;
  companyWebsite: string;
  companyActivity: string | null;
  addressStreet: string;
  addressNumber: string;
  addressComplement: string;
  addressPostalCode: string;
  addressNeighborhood: string;
  addressCity: string;
  addressState: string;
  colorPrimary: string;
  colorSecondary: string;
  logo: string | null;
  logoLarge: string | null;
  favicon: string | null;
  theme: "light" | "dark";
  language: "pt_BR" | "en";
  timezone: number;
  currency: "BRL" | "USD";
  limitWorkspaces: number;
  limitUsers: number;
  createdAt: string;
  expiresAt: string | null;
  updatedAt: string | null;
  deletedAt: string | null;
};
