export const Banks = [
  { code: "341", name: "Itaú Unibanco" },
  { code: "001", name: "Banco do Brasil" },
  { code: "237", name: "Bradesco" },
  { code: "104", name: "Caixa Econômica Federal" },
  { code: "033", name: "Santander Brasil" },
  { code: "208", name: "BTG Pactual" },
  { code: "748", name: "Sicredi" },
  { code: "756", name: "Sicoob" },
  { code: "422", name: "Banco Safra" },
  { code: "745", name: "Citibank Brasil" },
  { code: "041", name: "Banrisul" },
  { code: "655", name: "Banco Votorantim (BV)" },
  { code: "004", name: "Banco do Nordeste" },
  { code: "007", name: "BNDES" },
  { code: "246", name: "Banco ABC Brasil" },
  { code: "707", name: "Banco Daycoval" },
  { code: "623", name: "Banco PAN" },
  { code: "318", name: "Banco BMG" },
  { code: "747", name: "Banco Rabobank" },
  { code: "752", name: "Banco BNP Paribas Brasil" },
  { code: "743", name: "Banco J. Safra" },
  { code: "217", name: "Banco John Deere" },
  { code: null, name: "Banco KDB" },
  { code: null, name: "Banco KEB Hana do Brasil" },
  { code: "600", name: "Banco Luso Brasileiro" },
  { code: null, name: "Banco Máxima" },
  { code: null, name: "Banco Maxinvest" },
  { code: "389", name: "Banco Mercantil do Brasil" },
  { code: "370", name: "Banco Mizuho do Brasil" },
  { code: "746", name: "Banco Modal" },
  { code: null, name: "Banco Morgan Stanley" },
  { code: "456", name: "MUFG Brasil (Sumitomo Mitsui)" },
  {
    code: "007",
    name: "Banco Nacional de Desenvolvimento Econômico e Social (BNDES)",
  },
  { code: "721", name: "Banco Olé Bonsucesso Consignado" },
  { code: "712", name: "Banco Ourinvest" },
  { code: "623", name: "Banco PAN S.A." },
  { code: "611", name: "Banco Paulista" },
  { code: "643", name: "Banco Pine" },
  { code: null, name: "Banco Porto Real de Investimentos" },
  { code: "633", name: "Banco Rendimento" },
  { code: null, name: "Banco Ribeirão Preto" },
  { code: null, name: "Banco Rodobens" },
  { code: null, name: "Banco VR" },
  { code: null, name: "Banco Western Union do Brasil" },
  { code: null, name: "Banco Woori Bank do Brasil" },
  { code: "332", name: "Banco XP" },
  { code: null, name: "Banco Smartbank" },
  { code: "366", name: "Banco Société Générale Brasil" },
  { code: "637", name: "Banco Sofisa" },
  { code: "082", name: "Banco Topázio" },
  { code: "634", name: "Banco Triângulo" },
  { code: null, name: "Banco Tricury" },
  { code: "655", name: "Banco Volkswagen (VW)" },
  { code: "021", name: "Banestes (Banco do Espírito Santo)" },
  { code: "756", name: "Bancoob (BANCOOB)" },
  { code: null, name: "Banco Unicard" },
  { code: null, name: "Banco Unibanco (antigo)" },
  { code: null, name: "Banco Banif" },
  { code: "070", name: "BRB – Banco de Brasília" },
  { code: null, name: "Banco HyperCard" },
  { code: null, name: "Banco Opportunity" },
  { code: null, name: "Banco Dibens" },
  { code: null, name: "Banco Gerdau" },
  { code: null, name: "Banco GMAC" },
  { code: "399", name: "HSBC Bank Brasil (encerrado no varejo)" },
  { code: null, name: "Banco Citicard" },
  { code: null, name: "Banco CNH Capital" },
  { code: null, name: "Banco Calyon Brasil" },
  { code: null, name: "Banco Cacique" },
  { code: null, name: "Banco Itaú BBA" },
  { code: null, name: "Banco ItaúBank" },
  { code: null, name: "Banco Itaucred Financiamentos" },
  { code: null, name: "Banco Lemon" },
  { code: null, name: "Banco Garantia" },
  { code: "604", name: "Banco Industrial do Brasil" },
  { code: "125", name: "Banco Brasil Plural" },
  { code: "107", name: "Banco Bocom BBM" },
  { code: null, name: "Banco Arbi" },
  { code: null, name: "Banco Andbank" },
  { code: null, name: "Banco Afinz" },
  { code: null, name: "Banco BRP" },
  { code: "075", name: "Banco ABN AMRO" },
  { code: "121", name: "Banco Agibank" },
  { code: null, name: "Banco Bari" },
  { code: "336", name: "Banco C6 Bank" },
  { code: "260", name: "Nubank" },
  { code: "077", name: "Banco Inter" },
  { code: "735", name: "Neon" },
  { code: "290", name: "PagBank (PagSeguro)" },
  { code: "212", name: "Banco Original" },
  { code: "237", name: "Next (Bradesco)" },
];

export const BanksSafely = Banks.filter(function (bank) {
  return Boolean(bank.code);
}) as {
  code: string;
  name: string;
}[];
