const TranslatePt = {
  login: {
    login: "Entrar",
    instance: "Instância",
    username: "Usuário",
    password: "Senha",
    forgot_password: "Esqueci a senha",
  },
  menu: {
    financial: "Financeiro",
    dashboard: "Painel",
    orders: "Pedidos",
    inflows: "Entradas",
    outflows: "Saídas",
    statements: "Demonstrações",
    administrative: "Administrativo",
    customers: "Clientes",
    suppliers: "Fornecedores",
    employees: "Colaboradores",
    operational: "Operacional",
    products: "Produtos",
    services: "Serviços",
    vehicles: "Veículos",
    tools: "Ferramentas",
    documents: "Documentos",
    schedules: "Agendas",
    workspaces: "Organizações",
    integrations: "Integrações",
    accounts: "Contas",
    settings: "Configurações",
    logout: "Sair",
  },
  workspace: {
    workspaces: "Organizações",
    new: "Nova organização",
    name: "Nome da Organização",
    name_placeholder: "Ex. Setor 123",
    title_edit: "Edite a organização",
    title_create: "Crie uma nova organização",
    subtitle: "Preencha os campos abaixo para criar ou editar a organização",
    description_placeholder: "Uma breve descrição sobre a organização",
    units: "Unidades",
    teams: "Times",
    offices: "Escritórios",
    centers: "Centros",
    agencies: "Agências",
    branches: "Filias",
    sections: "Sessões",
    divisions: "Divisões",
    operations: "Operações",
    departments: "Departamentos",
    subsidiaries: "Subsidiárias",
    not_change_status: "Não é permitido desativar a organização selecionada",
    not_delete: "Não é permitido deletar a organização selecionada",
  },
  integrations: {
    integration: "Integração",
    integrations: "Integrações",
    mailersend: "MailerSend",
    mailersend_description: "Integração para o envio de emails.",
    twilio: "Twilio",
    twilio_description: "Integração para o disparo de SMS marketing.",
    stripe: "Stripe",
    stripe_description: "Integração para o gerar pagamentos.",
    openai: "OpenAI",
    openai_description: "Integração com serviço de Inteligência Artificial.",
    setup: "Configurar",
    wip: "Em desenvolvimento",
  },
  accounts: {
    account: "Conta",
    accounts: "Contas",
    new: "Nova conta",
    name: "Nome da conta",
    name_placeholder: "Ex. Minha conta primária",
    is_coorporate: "Empresarial ou Pessoal",
    corporate: "Empresarial",
    personal: "Pessoal",
    holder: "Nome do responsável",
    holder_placeholder: "Ex. Fulano de Tal",
    holder_document_1: "Documento (CPF/CNPJ)",
    holder_document_2: "Documento (RG)",
    holder_document_placeholder: "123.456.789-10",
    bank_code: "Código do banco",
    bank_name: "Nome do banco",
    bank_agency: "Agência",
    bank_account: "Conta",
    bank_number_placeholder: "123456",
    title_edit: "Edite a conta",
    title_create: "Crie uma nova conta",
    subtitle: "Preencha os campos abaixo para criar ou editar a conta",
  },
  settings: {
    settings: "Configurações",
  },
  pages: {
    error: "Erro",
    error_description: "Houve um erro ao acessar esta página",
    not_found: "Não encontrado",
    not_found_description: "Não foi encontrado a página que você acessou",
  },
  dialog: {
    title_delete: "Deletar",
    description_delete: "Deseja deletar o item selecionado?",
    title_workspace: "Selecione a organização",
  },
  toast: {
    // success
    success_login: "Logado com sucesso!",
    success_create: "O item foi criado com sucesso!",
    success_edit: "O item foi editado com sucesso!",
    success_delete: "O item foi deletado com sucesso!",
    success_workspace: "Organização selecionada com sucesso!",
    // warniang
    warning_create: "O item não foi criado!",
    warning_edit: "O item não foi editado!",
    warning_delete: "O item não foi deletado!",
    // error
    error_create: "Houve um erro ao criar o item!",
    error_edit: "Houve um erro ao editar o item!",
    error_delete: "Houve um erro ao deletar o item!",
  },
  components: {
    // buttons
    help: "Obtenha ajuda",
    edit: "Editar",
    delete: "Deletar",
    import: "Importar",
    export: "Exportar",
    back: "Voltar",
    close: "Fechar",
    cancel: "Cancelar",
    confirm: "Confirmar",
    save: "Salvar",
    // labels
    status: "Estado",
    active: "Ativado",
    inactive: "Desativado",
    user: "Usuário",
    category: "Categoria",
    description: "Descrição",
    // dates
    created_at: "Criado em",
    updated_at: "Atualizado em",
    deletedAt: "Desativado em",
    // others
    loading: "Carregando",
    search: "Faça a sua pesquisa...",
  },
  stacks: {
    // no
    no_option: "Nenhuma opção selecionada",
    no_description: "Sem descrição",
    no_items: "Nenhum item encontrado",
    no_instance: "Nenhum instância encontrada",
    no_token: "O token não foi encontrado",
    no_user: "Os dados do usuário não foram encontrado",
    no_workspace: "Nenhuma organização encontrada",
    no_integration: "Nenhuma integração encontrada",
    session_expired: "A sessão expirou",
    required_fields: "Os campos com asteriscos são obrigatórios",
    // fields
    wrong_credentials: "As credenciais estão incorretas",
    incorrect_length: "Tamanho incorreto",
    too_big: "Muito grande",
    invalid_string: "Texto inválido",
    invalid_type: "Tipo no formato inválido",
    not_finite: "Não finito",
    too_small: "Muito pequeno",
    invalid_phone_number: "Número de telefone inválido",
    invalid_document: "Documento inválido",
    invalid_date: "Data no formato inválido",
    invalid_id: "Id inválido",
    invalid_postal_code: "Código postal inválido",
  },
};

const TranslateEn = {
  login: {
    login: "Log In",
    instance: "Instance",
    username: "Username",
    password: "Password",
    forgot_password: "Forgot the password",
  },
  menu: {
    financial: "Financial",
    dashboard: "Dashboard",
    orders: "Orders",
    inflows: "Inflows",
    outflows: "outflows",
    statements: "Statements",
    administrative: "Administrative",
    customers: "Customers",
    suppliers: "Suppliers",
    employees: "Employees",
    operational: "Operational",
    products: "Products",
    services: "Services",
    vehicles: "Vehicles",
    tools: "Tools",
    documents: "Documents",
    schedules: "Schedules",
    workspaces: "Workspaces",
    integrations: "Integrations",
    accounts: "Accounts",
    settings: "Settings",
    logout: "Log out",
  },
  workspace: {
    workspaces: "Workspaces",
    new: "New workspace",
    name: "Workspace Name",
    name_placeholder: "e.g. Head Office",
    title_edit: "Edit the workspace",
    title_create: "Create a new workspace",
    subtitle: "Fill the below fields to create or edit the workspaces",
    description_placeholder: "A brief description about the workspace",
    units: "Units",
    teams: "Teams",
    offices: "Offices",
    centers: "Centers",
    agencies: "Agencies",
    branches: "Branches",
    sections: "Sections",
    divisions: "Divisions",
    operations: "Operations",
    departments: "Departments",
    subsidiaries: "Subdidiaries",
    not_change_status: "Not allowed disabled selected workspace",
    not_delete: "Not allowed delete selected workspace",
  },
  integrations: {
    integration: "Integration",
    integrations: "Integrations",
    mailersend: "MailerSend",
    mailersend_description: "Integration to send multiple emails.",
    twilio: "Twilio",
    twilio_description: "Integration to shooting SMS Marketing.",
    stripe: "Stripe",
    stripe_description: "Integration to generate order payments.",
    openai: "OpenAI",
    openai_description: "Integration to use Artificial Intelligence service.",
    setup: "Setup",
    wip: "Work in progress",
  },
  accounts: {
    account: "Account",
    accounts: "Accounts",
    new: "New account",
    name: "Account name",
    name_placeholder: "e.g My primary account",
    is_coorporate: "Corporate or Personal",
    corporate: "Corporate",
    personal: "Personal",
    holder: "Holder name",
    holder_placeholder: "e.g John Doe",
    holder_document_1: "Document 1",
    holder_document_2: "Document 2",
    holder_document_placeholder: "123 456 789 10",
    bank_code: "Bank code",
    bank_name: "Bank name",
    bank_agency: "Agency",
    bank_account: "Account",
    bank_number_placeholder: "123456",
    title_edit: "Edit the account",
    title_create: "Create a new account",
    subtitle: "Fill the below fields to create or edit the account",
  },
  settings: {
    settings: "Settings",
  },
  pages: {
    error: "Error",
    error_description: "An error occurred while accessing this page",
    not_found: "Not Found",
    not_found_description: "The page you accessed was not found",
  },
  dialog: {
    title_delete: "Delete",
    description_delete: "Do you want delete delete this item?",
    title_workspace: "Select the workspace",
  },
  toast: {
    // success
    success_login: "Logged with success!",
    success_create: "Item created with success!",
    success_edit: "Item edited with success!",
    success_delete: "Item deleted with success!",
    success_workspace: "Workspace selected with success!",
    // warning
    warning_create: "Item not created!",
    warning_edit: "Item not edited!",
    warning_delete: "Item not deleted!",
    // error
    error_create: "There was an error creating the item!",
    error_edit: "There was an error editing the item!",
    error_delete: "There was an error deleting the item!",
  },
  components: {
    // buttons
    help: "Get help",
    edit: "Edit",
    delete: "Delete",
    import: "Import",
    export: "Export",
    back: "Back",
    close: "Close",
    cancel: "Cancel",
    confirm: "Confirm",
    save: "Save",
    // labels
    status: "Status",
    active: "Active",
    inactive: "Inactive",
    user: "User",
    category: "Category",
    description: "Description",
    // dates
    created_at: "Created at",
    updated_at: "Updated at",
    deletedAt: "Disabled at",
    // others
    loading: "Loading",
    search: "Type here to search...",
  },
  stacks: {
    // no
    no_option: "No options selected",
    no_description: "No description",
    no_items: "No items found",
    no_instance: "No instance found",
    no_token: "No token found",
    no_user: "No user data found",
    no_workspace: "No workspaces found",
    no_integration: "No integration found",
    session_expired: "Your sessions is expired",
    required_fields: "The fields with asterics are required",
    // fields
    wrong_credentials: "Wrong credentials",
    incorrect_length: "Incorrect length",
    too_big: "Too big",
    invalid_string: "Invalid string",
    invalid_type: "Invalid type",
    not_finite: "Not finite",
    too_small: "Too small",
    invalid_phone_number: "Invalid phone number",
    invalid_document: "Invalid document",
    invalid_date: "Invalid date",
    invalid_id: "Invalid Id",
    invalid_postal_code: "Invalid postal code",
  },
};

const Translate = {
  pt: TranslatePt,
  en: TranslateEn,
};

export default Translate;
