const TranslatePt = {
  about: {
    title: "Sobre",
    description: "Forza Sistemas. Todos os direitos reservados.",
    version_backend: "Backend",
    version_frontend: "Frontend",
    uptime: "Tempo em atividade",
    website: "Website",
    api: "API",
    docs: "Documentação",
  },
  account: {
    account: "Conta Bancária",
    accounts: "Contas Bancárias",
    new: "Nova conta",
    name: "Nome da conta",
    name_placeholder: "Ex. Minha conta primária",
    is_coorporate: "Empresarial ou Pessoal",
    corporate: "Empresarial",
    personal: "Pessoal",
    holder: "Nome do responsável",
    holder_placeholder: "Ex. Fulano de Tal",
    holder_document_1: "Documento (CPF/CNPJ)",
    holder_document_2: "Documento (RG)",
    holder_document_placeholder: "123.456.789-10",
    bank_code: "Código do banco",
    bank_name: "Nome do banco",
    bank_agency: "Agência",
    bank_account: "Conta",
    bank_number_placeholder: "123456",
    title_edit: "Edite a conta",
    title_create: "Crie uma nova conta",
    subtitle: "Preencha os campos abaixo para criar ou editar a conta",
  },
  callout: {
    company_document_search:
      "Ao preencher o campo 'Documento (CNPJ)', será pesquisado e preenchido automaticamente os dados da empresa",
    person_mobile_search:
      "Ao preencher o campo 'Número de Celular', será preenchido automaticamente com os dados do WhatsApp",
    postal_code_search:
      "Ao preencher o campo 'Código Postal (CEP)', será buscado automaticamente o endereço através da base da dados pública",
    required_fields: "Os campos com asteriscos são obrigatórios",
    shipping_value:
      "Com o código postal do destinatário e do remetente, será mostrado as empresas disponíveis para realizar o envio desta venda",
  },
  components: {
    to_invoice: "Faturar",
    total: "Total",
    ai_short: "AI",
    ai_long: "Inteligência Artificial",
    translate: "Traduzir",
    restore: "Restaurar",
    other: "Outro",
    others: "Outros",
    document: "Documento",
    sms: "SMS",
    message: "Mensagem",
    email: "Email",
    pagination_showing: "Mostrando",
    pagination_of: "de",
    pagination_page: "páginas",
    pagination_items: "itens",
    master: "Mestre",
    admin: "Administrador",
    collaborator: "Colaborador",
    unknown: "Desconhecido",
    download: "Baixar",
    copy_id: "Copiar Id",
    timezone: "Fuso horário",
    language: "Idioma",
    theme: "Tema",
    light: "Claro",
    dark: "Escuro",
    date_format: "Formato da data",
    currency: "Moeda",
    "dd/MM/yyyy": "dia/mês/ano",
    "MM/dd/yyyy": "mês/dia/ano",
    "yyyy-MM-dd": "ano-mês-dia",
    all: "Todos",
    photo: "Foto",
    image: "Imagem",
    to: "Para",
    by: "Por",
    // editor
    bold: "Negrito",
    italic: "Itálico",
    underline: "Sublinhado",
    strikethrough: "Tachado",
    title: "Título",
    subtitle: "Subtítulo",
    left: "Esquerda",
    center: "Centralizar",
    right: "Direita",
    justify: "Justificar",
    ol: "Lista ordenada",
    ul: "Lista desordenada",
    // format
    json: "Formato JSON",
    xlsx: "Planilha Excel",
    csv: "Arquivo CSV",
    // address
    address_street: "Rua",
    address_street_placeholder: "Ex. Rua Azul",
    address_number: "Número",
    address_number_placeholder: "Ex. 123",
    address_complement: "Complemento",
    address_complement_placeholder: "Ex. Apto 1",
    address_postal_code: "Código Postal (CEP)",
    address_postal_code_placeholder: "12345-123",
    address_neighborhood: "Bairro",
    address_neighborhood_placeholder: "Ex. Arco-iris",
    address_city: "Cidade",
    address_city_placeholder: "Ex. Cores",
    address_state: "Estado",
    // buttons
    yes: "Sim",
    no: "Não",
    copy: "Copiar",
    share: "Compartilhar",
    undo: "Desfazer",
    redo: "Refazer",
    open_game: "Abrir jogo",
    remove: "Remover",
    add: "Adicionar",
    help: "Obtenha ajuda",
    edit: "Editar",
    delete: "Deletar",
    delete_permanently: "Deletar permanentemente",
    import: "Importar",
    export: "Exportar",
    back: "Voltar",
    open: "Abrir",
    close: "Fechar",
    cancel: "Cancelar",
    confirm: "Confirmar",
    save: "Salvar",
    // labels
    shelves: "Estante",
    table: "Tabela",
    empty_name: "Nome vazio",
    status: "Estado",
    active: "Ativado",
    inactive: "Desativado",
    user: "Usuário",
    category: "Categoria",
    description: "Descrição",
    choose_file: "Escolha o arquivo",
    no_file_choosen: "Nenhum arquivo escolhido",
    // dates
    no_filter_date: "Sem data",
    today: "Hoje",
    this_week: "Esta semana",
    this_month: "Este mês",
    created_at: "Criado em",
    updated_at: "Atualizado em",
    deletedAt: "Desativado em",
    // others
    loading: "Carregando",
    search: "Faça a sua pesquisa...",
  },
  customer: {
    // list
    customer: "Cliente",
    customers: "Clientes",
    new: "Novo cliente",
    // inputs
    name: "Nome do cliente",
    description: "Descrição",
    document: "Documento",
    mobile: "Número de celular",
    email: "Email",
    document_1: "Documento (CNPJ)",
    document_2: "Documento (CPF, RG...)",
    phone_1: "Número Telefone 1",
    phone_2: "Número Telefone 2",
    representative_name: "Nome do representante",
    address: "Endereço",
    representative_role: "Função do representante",
    // placeholders
    name_placeholder: "Ex. Fulano LTDA",
    description_placeholder: "Digite aqui uma breve descrição sobre o cliente",
    mobile_placeholder: "Ex. +55 (11) 98888-7777",
    phone_placeholder: "Ex. +55 (11) 4040-3030",
    email_placeholder: "Ex. fulano@email.com",
    document_1_placeholder: "Ex. 11.222.333/0001-44",
    document_2_placeholder: "Ex. 111.222.333-44",
    representative_name_placeholder: "Ex. Fulano de Tal",
    representative_role_placeholder: "Ex. Diretor",
    // titles and subtitles
    title_edit: "Edite o cliente",
    title_create: "Crie um novo cliente",
    subtitle: "Preencha as entradas para criar ou editar o cliente",
    title_representative: "Representante",
    subtitle_representative:
      "Preencha as entradas com os dados do representante",
    title_addresses: "Endereço",
    subtitle_addresses: "Preencha as entradas com os dados de endereço",
    // messages
    no_delete_address: "Não é possível deletar todos os endereços",
  },
  dashboard: {
    dashboard: "Painel",
    stats_inflows_title: "Entradas",
    stats_inflows_description: "Total de entradas já realizadas",
    stats_inflows_receive_title: "Entradas a receber",
    stats_inflows_receive_description:
      "Total de entradas que ainda serão recebidas",
    stats_inflows_late_title: "Entradas em atraso",
    stats_inflows_late_description:
      "Total de entradas que já deveriam ter sido recebidas",
    stats_outflows_title: "Saídas",
    stats_outflows_description: "Total de saídas já realizadas",
    stats_outflows_receive_title: "Saídas a receber",
    stats_outflows_receive_description:
      "Total de saídas que ainda serão realizadas",
    stats_outflows_late_title: "Saídas em atraso",
    stats_outflows_late_description:
      "Total de saídas que já deveriam ter sido realizadas",
    chart_inflows_title: "Entradas Financeiras",
    chart_inflows_description:
      "As entradas distribuídas ao longo do intervalo de tempo.",
    chart_outflows_title: "Saídas Financeiras",
    chart_outflows_description:
      "As saídas distribuídas ao longo do intervalo de tempo.",
    chart_inflows_resume_title: "Resumo de Entradas",
    chart_inflows_resume_description:
      "Visualização das entradas a receber e em atraso.",
    chart_outflows_resume_title: "Resumo de Saídas",
    chart_outflows_resume_description:
      "Visualização das saídas a receber e em atraso.",
  },
  dialog: {
    title_delete: "Deletar",
    description_delete: "Deseja deletar o item selecionado?",
    title_workspace: "Selecione a organização",
    title_share: "Compartilhar",
    description_share:
      "Compartilhe o item com outras pessoas através dos botões abaixo:",
    title_close: "Fechar",
    description_close: "Deseja realmente fechar este item?",
  },
  document: {
    placeholder: "Digite aqui o conteúdo do seu documento...",
    document: "Documento",
    documents: "Documentos",
    new: "Novo documento",
    type: "Tipo",
    is_public: "Está publico?",
    name: "Nome do documento",
    name_placeholder: "Ex. Meu primeiro documento",
    ai_text: "Texto com IA",
    ai_correct: "Corrigir com IA",
    documents_size: "Tamanho",
    documents_type: "Tipo",
    documents_total_title: "Total",
    documents_total_description:
      "Total de documentos que foram salvos no sistema",
    documents_relation_title: "Relações",
    documents_relation_description:
      "Total de relações que foram feitas entre o documento e outros módulos do sistema",
    relations: "relações",
    information: "Informação",
    quantity: "Quantidade",
    public: "Público",
    private: "Privado",
    document_private: "Este documento está privado",
    not_public: "Este documento não está publico",
    recycle_bin: "Lixeira",
    open_recycle_bin: "Abrir a lixeira",
  },
  integration: {
    integration: "Integração",
    integrations: "Integrações",
    mailersend: "MailerSend",
    mailersend_description: "Integração para o envio de emails.",
    twilio: "Twilio",
    twilio_description: "Integração para o disparo de SMS marketing.",
    stripe: "Stripe",
    stripe_description: "Integração para o gerar pagamentos.",
    openai: "OpenAI",
    openai_description:
      "Integração com serviço da OpenAI de Inteligência Artificial.",
    mailchimp: "Mailchimp",
    mailchimp_description: "Integração para enviar multiples email marketing.",
    paypal: "PayPal",
    paypal_description:
      "Integração para gerenciamento de dinheiro e pagamentos.",
    gemini: "Gemini",
    gemini_description:
      "Integração com serviço da Google de Inteligência Artificial.",
    mercadolibre: "Mercado Livre",
    mercadolibre_description: "Integração para venda de produtos.",
    sales: "Vendas",
    comunications: "Comunicação",
    payments: "Pagementos",
    ai: "Inteligência Artificial",
    setup: "Configurar",
    wip: "Em desenvolvimento",
    beta: "Em beta",
  },
  login: {
    login: "Entrar",
    instance: "Instância",
    username: "Usuário",
    password: "Senha",
    forgot_password: "Esqueci a senha",
  },
  menu: {
    financial: "Financeiro",
    dashboard: "Painel",
    orders: "Ordens",
    inflows: "Receitas",
    outflows: "Despesas",
    statements: "Demonstrações",
    recurrences: "Recorrências",
    administrative: "Administrativo",
    customers: "Clientes",
    suppliers: "Fornecedores",
    users: "Usuários",
    operational: "Operacional",
    products: "Produtos",
    sales: "Vendas",
    services: "Serviços",
    vehicles: "Veículos",
    tools: "Ferramentas",
    automations: "Automações",
    documents: "Documentos",
    schedules: "Agendas",
    workspaces: "Organizações",
    integrations: "Integrações",
    accounts: "Contas Bancárias",
    settings: "Configurações",
    about: "Sobre",
    logout: "Sair",
  },
  order: {
    order: "Ordem",
    orders: "Ordens",
    new: "Nova ordem",
    title_edit: "Edite a ordem",
    title_create: "Crie uma nova ordem",
    subtitle: "Preencha os dados abaixo para poder editar ou criar a ordem",
    title_document: "Documentos",
    subtitle_document:
      "Selecione os documentos para serem anexados com a ordem",
    services: "Serviços",
    title_addresses: "Endereços",
    subtitle_addresses:
      "Coloque aqui todos os endereços relacionados com a ordem",
    title_transport: "Deslocamento",
    subtitle_transport:
      "Preencha os dados relacionados ao deslocamento da ordem de serviço",
    // stages
    draft: "Rascunho",
    open: "Aberto",
    pending: "Pendente",
    review: "Revisão",
    progress: "Progresso",
    completed: "Completado",
    canceled: "Cancelado",
    // filters
    all_stages: "Todos estágios",
    all_users: "Todos responsáveis",
    all_providers: "Todos prestadores",
    // list
    id: "Identificação",
    stage: "Estágio",
    customer: "Cliente",
    service_name: "Nome do serviço",
    details: "Detalhes",
    empty_details: "Detalhes vazio",
    account: "Conta bancária",
    addition: "Acréscimo",
    deduction: "Dedução",
    provider: "Prestador",
    user: "Responsável",
    addresses: "Endereços",
    // inspect
    date_start: "Data de início",
    date_estimated: "Date prevista para término",
    date_end: "Data de término",
    no_services: "Sem serviços",
    no_details: "Sem detalhes",
    some_invalid_detail: "Algum detalhe está inválido",
    description_placeholder: "Digite aqui uma breve descrição sobre essa ordem",
    quantity: "Quantidade",
    quantity_placeholder: "Ex. 2 quantidade",
    price: "Valor",
    method: "Método",
    vehicle: "Veículo",
    driver: "Motorista",
    // details
    details_title: "Detalhes",
    details_title_placeholder: "Ex. Impostos, Taxas",
    details_type: "Tipo do detalhe",
    details_mode: "Modo do detalhe",
    details_amount: "Quantia",
    details_percent: "Porcentagem",
    tax: "Imposto",
    discount: "Desconto",
    promo: "Promoção",
    fee: "Taxa",
    coupon: "Cupom",
    voucher: "Vale",
    percent: "Porcentagem",
    amount: "Quantia",
    // documents
    open_quotation: "Abrir cotação",
    document_quotation: "Documento de cotação",
    open_contract: "Abrir contrato",
    document_contract: "Documento de contrato",
  },
  pages: {
    error: "Erro",
    error_description: "Houve um erro ao acessar esta página",
    not_found: "Não encontrado",
    not_found_description: "Não foi encontrado a página que você acessou",
  },
  product: {
    product: "Produto",
    products: "Produtos",
    new: "Novo produto",
    no_delete_all_variants: "Não é possível apagar todas as variações",
    physical: "Físico",
    digital: "Digital",
    name: "Nome do produto",
    name_placeholder: "Ex. Camiseta Branca",
    description_placeholder: "Ex. Uma breve descrição do produto...",
    type: "Tipo",
    category: "Categoria",
    single: "Único",
    variant: "Variante",
    variants: "Variações",
    photo: "Foto",
    price: "Preço",
    title_edit: "Edite o produto",
    title_create: "Crie um novo produto",
    subtitle: "Preencha os campos abaixo para criar ou editar o produto",
    title_variants: "Variações do produto",
    subtitle_variants: "Preencha os campos abaixo com os dados do produto",
    id: "Id",
    variant_name: "Nome da variação",
    variant_name_placeholder: "Ex. Camiseta Branca G (Grande)",
    title_specifications: "Especificações",
    subtitle_specifications:
      "Se o produto tiver alguma especificação digital ou online",
    specific_author: "Autor",
    specific_publisher: "Editora",
    specific_format: "Formato",
    specific_size: "Tamanho",
    specific_url: "Endereço de URL",
    specific_version: "Versão",
    specific_license: "Licença",
    lifetime: "Vitalício",
    subscription: "Assinatura",
    single_use: "Uso único",
    specific_access: "Acesso",
    download: "Download",
    streaming: "Streaming",
    cloud: "Cloud",
    external: "Externo",
    specific_method: "Método",
    website: "Website",
    email: "Email",
    service: "Serviço",
    property_brand: "Marca",
    property_model: "Modelo",
    property_year: "Ano",
    property_color: "Cor",
    property_series: "Serie",
    property_origin: "Origem",
    property_warranty: "Garantia",
    property_material: "Material",
    specific_condition: "Condição",
    condition_new: "Novo",
    condition_used: "Usado",
    title_properties: "Propriedades",
    subtitle_properties: "Se o produto tiver várias propriedades físicas",
    attribute_weight: "Peso",
    attribute_height: "Altura",
    attribute_length: "Comprimento",
    attribute_depth: "Profundidade",
    attribute_capacity: "Capacidade",
    attribute_volume: "Volume",
    title_attributes: "Atributos",
    subtitle_attributes:
      "Se o produto tem atributos para o enviou ou recebimento",
  },
  sale: {
    sale: "Venda",
    sales: "Vendas",
    new: "Nova venda",
    stage: "Estágio",
    all_stage: "Todos estágios",
    id: "Identificação",
    customer: "Cliente",
    user: "Responsável",
    seller: "Vendedor",
    all_seller: "Todos vendendores",
    account: "Conta bancária",
    description_placeholder: "Preencha aqui uma descrição sobre a venda...",
    addition: "Acréscimo",
    deduction: "Dedução",
    subtotal: "Subtotal",
    title_edit: "Edite a venda",
    title_create: "Crie uma nova venda",
    subtitle: "Preencha os dados abaixo para poder editar ou criar a venda",
    title_stage: "Estágios da venda",
    subtitle_stage: "Preencha as dadas dos estagios desta venda",
    title_address: "Logística da venda",
    subtitle_address: "Preencha com as informações de endereço dessa venda",
    title_document: "Documento da venda",
    subtitle_document:
      "Selecione o documento de proposta e contrato dessa venda",
    // stages
    funnel: "Estágios do funil",
    closing: "Estágios de fechamento",
    draft: "Rascunho",
    open: "Aberto",
    pending: "Pendente",
    paid: "Pago",
    proposal: "Proposta",
    negotiation: "Negociação",
    won: "Ganho",
    lost: "Perdido",
    processing: "Processando",
    shipped: "Enviado",
    completed: "Completo",
    canceled: "Cancelado",
    failed: "Falhou",
    refunded: "Reembolsado",
    returned: "Retornado",
    disputed: "Contestado",
    // products
    product_name: "Nome do produto",
    variant_name: "Nome da variação",
    quantity: "Quantidade",
    quantity_placeholder: "Ex. 2 produtos",
    price: "Valor",
    no_products: "Nenhum produto adicionado",
    // details
    details: "Detalhes",
    details_type: "Tipo",
    details_mode: "Modo",
    details_amount: "Quantia",
    details_percent: "Porcentagem",
    details_title: "Motivo do detalhe",
    details_title_placeholder: "Ex. Taxa de compra",
    empty_details: "Detalhes vazio",
    some_invalid_detail: "Existe algum detalhe com o valor inválido",
    no_details: "Nenhum detalhe adicionado",
    tax: "Imposto",
    discount: "Desconto",
    promo: "Promoção",
    fee: "Taxa",
    coupon: "Cupom",
    voucher: "Vale",
    percent: "Porcentagem",
    amount: "Quantia",
    // dates
    date_won: "Data de ganho",
    date_lost: "Data de perdido",
    // shipping
    shipping: "Envio",
    shipping_method: "Método de envio",
    shipping_cost: "Valor do envio",
    shipping_description: "Descrição do envio",
    shipping_description_placeholder: "Ex. Enviado por Encomenda LTDA",
    shipping_from_postal: "Código postal do remetente",
    shipping_from_address: "Logradouro do remetente",
    shipping_to_postal: "Código postal do destinatário",
    shipping_to_address: "Logradouro do destinatário",
    standard: "Envio correios",
    express: "Envio expresso",
    pickup_store: "Retirada na loja",
    pickup_partner: "Retirada por parceiro",
    freight: "Frete",
    dropshipping: "Dropshipping",
    delivery: "Entrega local",
    // documents
    document_proposal: "Documento de proposta",
    document_contract: "Documento de contrato",
    open_proposal: "Abrir proposta",
    open_contract: "Abrir contrato",
  },
  schedule: {
    schedule: "Agenda",
    schedules: "Agendas",
    all_day: "Dia inteiro",
    previous: "Anterior",
    next: "Próximo",
    today: "Hoje",
    month: "Mês",
    week: "Semana",
    day: "Dia",
    agenda: "Agenda",
    date: "Data",
    time: "Hora",
    event: "Evento",
    no_events_in_range: "Nenhum evento neste período.",
    title: "Título",
    no_title: "Sem título",
    title_placeholder: "Ex. Reunião matinal",
    description: "Descrição",
    no_description: "Sem descrição",
    description_placeholder:
      "Ex. Uma reunião que irá ocorrer na manhã do dia...",
    category: "Categoria",
    task: "Tarefa",
    note: "Anotação",
    remind: "Lembrete",
    deadline: "Prazo",
    work: "Trabalho",
    reserved: "Reserva",
    meeting: "Reunião",
    priority: "Prioridade",
    none: "Sem prioridade",
    low: "Baixa",
    medium: "Média",
    high: "Alta",
    critical: "Crítico",
    start_date: "Data e hora inicial",
    end_date: "Date e hora final",
    more: "mais",
  },
  service: {
    service: "Serviço",
    services: "Serviços",
    new: "Novo serviço",
    physical: "Físico",
    digital: "Digital",
    type: "Tipo",
    pricing_method: "Cobrar por",
    hourly: "Por hora",
    daily: "Por dia",
    weekly: "Semanalmente",
    monthly: "Mensalmente",
    one_time: "Por serviço",
    per_delivery: "Por entrega",
    name: "Nome do serviço",
    name_placeholder: "Ex. Instalações de estruturas metálicas",
    pricing_value: "Preço",
    title_edit: "Edite o serviço",
    title_create: "Crie um novo serviço",
    subtitle: "Preencha os campos abaixo para criar ou editar o serviço",
    description_placeholder: "Descreva o processo deste serviço...",
  },
  settings: {
    settings: "Configurações",
    title_preferences: "Preferências",
    subtitle_preferences:
      "Preencha os campos baixo para editar os dados de prefência da instância",
    title_apparence: "Aparência",
    subtitle_apparence:
      "Preencha os campos baixo para editar os dados de aparência da instância",
    title_company: "Empresa",
    subtitle_company:
      "Preencha os campos abaixo para editar os dados da empresa",
    title_address: "Endereço",
    subtitle_address:
      "Preencha os campos baixo para editar os dados do endereço",
    company_name: "Nome da empresa",
    company_name_placeholder: "Ex. Fulano de Tal LTDA",
    company_mobile: "Número de celular",
    company_phone: "Número de telefone",
    company_phone_placeholder: "+55 (11) 98888-7777",
    company_email: "Email",
    company_email_placeholder: "Ex. fulanotal@email.com",
    company_website: "Website",
    company_website_placeholder: "https://",
    company_activity: "Atividade",
    logo: "Logo",
    logoLarge: "Logo grande",
    favicon: "Favicon",
    color_primary: "Color primária",
    color_secondary: "Color secundaria",
    // options
    industry: "Indústria",
    commerce: "Comércio",
    services: "Serviços",
    agribusiness: "Agronegócio",
    construction: "Construção",
    logistics_and_transportation: "Logística e Transporte",
    education: "Educação",
    healthcare: "Saúde",
    it_and_software: "TI e Software",
    financial_services: "Financeiro",
    advertising_and_communication: "Publicidade e Comunicação",
    public_sector: "Setor Público",
    non_profits_and_foundations: "ONGs e Fundações",
    import_and_export: "Importação e Exportação",
    energy_and_utilities: "Energia",
    mining_and_extraction: "Mineração",
  },
  stacks: {
    // no
    no_name: "Sem nome",
    no_action: "Nenhuma ação encontrada",
    no_entity: "Nenhum módulo encontrado",
    no_email: "Sem email",
    no_phone: "Sem telefone",
    no_document: "Sem documento",
    no_find_item: "O item não foi encontrado",
    no_option: "Nenhuma opção selecionada",
    no_description: "Sem descrição",
    no_items: "Nenhum item encontrado",
    no_instance: "Nenhum instância encontrada",
    no_token: "O token não foi encontrado",
    no_user: "Os dados do usuário não foram encontrado",
    no_workspace: "Nenhuma organização encontrada",
    no_integration: "Nenhuma integração encontrada",
    session_expired: "A sessão expirou",
    no_address: "Sem endereço",
    // limit
    limit_workspace: "Limite de organizações foi atingida",
    limit_user: "Limite de usuários foi atingida",
    wrong_file_format: "O arquivo está com o formato errado",
    limit_image_5mb: "A imagem excede o limite de 5MB",
    // fields
    invalid_enum_value: "Valor desconhecido",
    wrong_credentials: "As credenciais estão incorretas",
    incorrect_length: "Tamanho incorreto",
    too_big: "Muito grande",
    invalid_string: "Texto inválido",
    invalid_type: "Tipo no formato inválido",
    not_finite: "Não finito",
    too_small: "Muito pequeno",
    invalid_phone_number: "Número de telefone inválido",
    invalid_document: "Documento inválido",
    invalid_date: "Data no formato inválido",
    invalid_id: "Id inválido",
    invalid_postal_code: "Código postal inválido",
  },
  supplier: {
    // list
    supplier: "Fornecedor",
    suppliers: "Fornecedores",
    new: "Novo forncedor",
    // inputs
    name: "Nome do fornecedor",
    document_1: "Documento (CNPJ)",
    mobile: "Número de celular",
    phone_1: "Número de telefone 1",
    email: "Email",
    description: "Descrição",
    representative_name: "Nome do representante",
    representative_role: "Função do representante",
    phone_2: "Número de telefone 2",
    document_2: "Document (CPF, RG...)",
    address: "Endereço",
    // placeholders
    name_placeholder: "Ex. Fulano de LTDA",
    document_1_placeholder: "Ex. 11.222.333/0001-44",
    mobile_placeholder: "Ex. +55 (11) 98888-7777",
    phone_placeholder: "Ex. +55 (11) 4040-3030",
    email_placeholder: "Ex. fulano@email.com",
    description_placeholder:
      "Escreva aqui uma breve descrição sobre o fornecedor",
    representative_name_placeholder: "Ex. Fulano de Tal",
    representative_role_placeholder: "Ex. Diretor",
    document_2_placeholder: "Ex. 111.222.333-44",
    // titles and subtitles
    title_edit: "Edite o fornecedor",
    title_create: "Crie um novo fornecedor",
    subtitle: "Preencha as entradas para editar ou criar o fornecedor",
    title_representative: "Representantes",
    subtitle_representative:
      "Preencha as entradas com os dados do representante",
    title_addresses: "Endereços",
    subtitle_addresses: "Preencha as entradas com os dados de endereço",
    // messages
    no_delete_address: "Não é possível excluir todos os endereços",
  },
  toast: {
    // title
    success: "Sucesso!",
    warning_error: "Oops!",
    loading: "Carregando...",
    // success
    success_restore: "O item foi restaurado.",
    success_find: "O item foi encontrado.",
    success_download: "O item foi baixado.",
    success_copy: "O id do item foi copiado.",
    success_login: "Você foi logado.",
    success_create: "O item foi criado.",
    success_edit: "O item foi editado.",
    success_delete: "O item foi deletado.",
    success_workspace: "A organização foi selecionada.",
    // warning
    warning_restore: "O item não foi restaurado.",
    warning_find: "O item não foi encontrado.",
    warning_create: "O item não foi criado.",
    warning_edit: "O item não foi editado.",
    warning_delete: "O item não foi deletado.",
    warning_copy: "O id não foi copiado.",
    // error
    error_restore: "Houve um erro ao restaurar o item.",
    error_create: "Houve um erro ao criar o item.",
    error_edit: "Houve um erro ao editar o item.",
    error_delete: "Houve um erro ao deletar o item.",
  },
  user: {
    user: "Usuário",
    users: "Usuários",
    new: "Novo usuário",
    title_edit: "Edite o usuário",
    title_create: "Crie um novo usuário",
    subtitle: "Preencha os campos abaixo para criar ou editar o usuário",
    role: "Função",
    name: "Nome do usuário",
    name_placeholder: "Ex. Fulano de Tal",
    document: "Documento",
    photo: "Foto",
    mobile: "Número de celular",
    email: "Email",
    address: "Endereço",
    document_1: "Documento (CPF)",
    document_2: "Documento (RG)",
    document_placeholder: "123.456.789-10",
    phone: "Número de telefone",
    phone_placeholder: "+55 (11) 1234-5678",
    email_placeholder: "Ex. fulanotal@empresa.com",
    title_audit: "Auditoria",
    subtitle_audit: "Veja todos os registros de ações do usuário",
    title_address: "Endereço do usuário",
    subtitle_address:
      "Preencha os campos abaixo com os dados de endereço do usuário",
    schedules_title: "Horários reservados",
    schedules_description:
      "Todos os horários que foram reservados na agenda deste usuário",
    not_change_status: "Não é permitido desativar o próprio usuário",
    // audit
    insert: "Criado",
    create: "Criado",
    read: "Consultado",
    update: "Atualizado",
    delete: "Deletado",
    to_audit: "Auditar",
    audit: "Auditoria",
    user_id: "Responsável",
    action: "Ação",
    entity: "Módulo",
    snapshot_name: "Nome",
    workspace: "Organização",
  },
  vehicle: {
    vehicle: "Veículo",
    vehicles: "Veículos",
    new: "Novo veículo",
    category: "Categoria",
    motocycle: "Moto",
    pickup: "Caminhonete",
    truck: "Caminhão",
    passenger: "Passeio",
    commercial: "Comercial",
    cargo_light: "Carga leve",
    cargo: "Cargueiro",
    cargo_heavy: "Carga pesada",
    transport: "Transporte",
    vintage: "Coleção",
    competition: "Competição",
    polylift_single: "Poliguindaste simples",
    polylift_double: "Poliguindaste duplo",
    hydro_vacuum: "Hidrovacuo",
    rollon_rolloff: "Rollon e Rolloff",
    bus: "Ônibus",
    tractor: "Trator",
    trailer: "Trailer",
    tricycle: "Triciclo",
    quadricycle: "Quadriciclo",
    buggy: "Buggy",
    special: "Especial",
    others: "Outros",
    utility: "Utilitário",
    name: "Nome do veículo",
    name_placeholder: "Ex. Ford Mustang",
    plate: "Placa",
    plate_brazil: "Placa Brasil",
    plate_mercosul: "Placa Mercosul",
    plate_type: "Tipo de placa",
    plate_brazil_placeholder: "ABC-1234",
    plate_mercosul_placeholder: "ABC1D34",
    brand: "Marca",
    brand_placeholder: "Ex. Ford",
    model: "Modelo",
    model_placeholder: "Ex. Mustang",
    chassi: "Número do chassi",
    color: "Cor predominante",
    year: "Ano",
    description_placeholder:
      "Escreve aqui todos os detalhes sobre o veículo...",
    title_edit: "Edite o veículo",
    title_create: "Crie um novo veículo",
    subtitle: "Preencha os campos abaixo para criar ou editar o veículo",
    document: "Documento (RENAVAM)",
    document_placeholder: "1234567890",
    maintenance: "Manutenção",
    refuel: "Abastecimento",
    no_brand: "Sem marca",
    no_model: "Sem modelo",
  },
  workspace: {
    workspaces: "Organizações",
    new: "Nova organização",
    name: "Nome da Organização",
    name_placeholder: "Ex. Setor 123",
    title_edit: "Edite a organização",
    title_create: "Crie uma nova organização",
    subtitle: "Preencha os campos abaixo para criar ou editar a organização",
    description_placeholder: "Uma breve descrição sobre a organização",
    units: "Unidades",
    teams: "Times",
    offices: "Escritórios",
    centers: "Centros",
    agencies: "Agências",
    branches: "Filias",
    sections: "Sessões",
    divisions: "Divisões",
    operations: "Operações",
    departments: "Departamentos",
    subsidiaries: "Subsidiárias",
    not_change_status: "Não é permitido desativar a organização selecionada",
    not_delete: "Não é permitido deletar a organização selecionada",
    already_selected_workspace: "Essa organização já foi selecionada!",
  },
};

const TranslateEn = {
  about: {
    title: "About",
    description: "Forza Sistemas. All rights reserved.",
    version_backend: "Backend",
    version_frontend: "Frontend",
    uptime: "Uptime",
    website: "Website",
    api: "API",
    docs: "Documentation",
  },
  account: {
    account: "Bank Account",
    accounts: "Banks Accounts",
    new: "New account",
    name: "Account name",
    name_placeholder: "e.g My primary account",
    is_coorporate: "Corporate or Personal",
    corporate: "Corporate",
    personal: "Personal",
    holder: "Holder name",
    holder_placeholder: "e.g John Doe",
    holder_document_1: "Document 1",
    holder_document_2: "Document 2",
    holder_document_placeholder: "123 456 789 10",
    bank_code: "Bank code",
    bank_name: "Bank name",
    bank_agency: "Agency",
    bank_account: "Account",
    bank_number_placeholder: "123456",
    title_edit: "Edit the account",
    title_create: "Create a new account",
    subtitle: "Fill the below fields to create or edit the account",
  },
  callout: {
    company_document_search:
      "When filling in the 'Document' field, the company's information will be automatically searched and filled in.",
    person_mobile_search:
      "When filling in the 'Mobile' field, the information will be automatically filled in using WhatsApp data.",
    postal_code_search:
      "When filling in the 'Postal Code (ZIP)' field, the address will be automatically retrieved from the public database.",
    required_fields: "Fields marked with an asterisk are required",
    shipping_value:
      "With the recipient's and sender's postal code, the companies available to ship this sale will be shown.",
  },
  components: {
    to_invoice: "To invoice",
    total: "Total",
    ai_short: "AI",
    ai_long: "Artificial Intelligence",
    translate: "Translate",
    restore: "Restore",
    other: "Other",
    others: "Others",
    document: "Document",
    sms: "SMS",
    message: "Message",
    email: "Email",
    pagination_showing: "Showing",
    pagination_of: "of",
    pagination_page: "pages",
    pagination_items: "items",
    master: "Master",
    admin: "Administrator",
    collaborator: "Collaborator",
    unknown: "Unknown",
    download: "Download",
    copy_id: "Copy Id",
    timezone: "Timezone",
    language: "Language",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    date_format: "Date format",
    currency: "Currency",
    "dd/MM/yyyy": "day/month/year",
    "MM/dd/yyyy": "month/day/year",
    "yyyy-MM-dd": "year-month-day",
    all: "All",
    photo: "Photo",
    image: "Image",
    to: "To",
    by: "By",
    // editor
    bold: "Bold",
    italic: "Italic",
    underline: "Underline",
    strikethrough: "Strikethrough",
    title: "Title",
    subtitle: "Subtitle",
    left: "Left",
    center: "Center",
    right: "Right",
    justify: "Justify",
    ol: "Ordened list",
    ul: "Unordered list",
    // format
    json: "Format JSON",
    xlsx: "Sheets Excel",
    csv: "File CSV",
    // address
    address_street: "Street",
    address_street_placeholder: "e.g. St Blue",
    address_number: "Number",
    address_number_placeholder: "e.g. 123",
    address_complement: "Complement",
    address_complement_placeholder: "e.g. Ap 1",
    address_postal_code: "Postal Code (ZIP Code)",
    address_postal_code_placeholder: "12345-123",
    address_neighborhood: "Region",
    address_neighborhood_placeholder: "e.g. Rainbow",
    address_city: "City",
    address_city_placeholder: "e.g. Colors",
    address_state: "State",
    // buttons
    yes: "Yes",
    no: "No",
    copy: "Copy",
    share: "Share",
    undo: "Undo",
    redo: "Redo",
    open_game: "Open game",
    remove: "Remove",
    add: "Add",
    help: "Get help",
    edit: "Edit",
    delete: "Delete",
    delete_permanently: "Delete Permanently",
    import: "Import",
    export: "Export",
    back: "Back",
    open: "Open",
    close: "Close",
    cancel: "Cancel",
    confirm: "Confirm",
    save: "Save",
    // labels
    shelves: "Shelves",
    table: "Table",
    empty_name: "Empty name",
    status: "Status",
    active: "Active",
    inactive: "Inactive",
    user: "User",
    category: "Category",
    description: "Description",
    choose_file: "Choose file",
    no_file_choosen: "No files choosen",
    // dates
    no_filter_date: "No date",
    today: "Today",
    this_week: "This week",
    this_month: "This month",
    created_at: "Created at",
    updated_at: "Updated at",
    deletedAt: "Disabled at",
    // others
    loading: "Loading",
    search: "Type here to search...",
  },
  customer: {
    // list
    customer: "Customer",
    customers: "Customers",
    new: "New customer",
    // inputs
    name: "Customer name",
    description: "Description",
    document: "Document",
    mobile: "Mobile",
    email: "Email",
    document_1: "Document 1",
    document_2: "Document 2",
    phone_1: "Phone 1",
    phone_2: "Phone 2",
    representative_name: "Representative name",
    representative_role: "Representative Role",
    address: "Address",
    // placeholders
    name_placeholder: "e.g. John Doe Inc",
    description_placeholder: "Type here a brief description about the customer",
    mobile_placeholder: "e.g +1 (234) 555-6666",
    phone_placeholder: "e.g +1 (234) 555-6666",
    email_placeholder: "e.g. johndoe@email.com",
    document_1_placeholder: "e.g. 11.222.333/0001-44",
    document_2_placeholder: "e.g. 111.222.333-44",
    representative_name_placeholder: "e.g. John Doe",
    representative_role_placeholder: "e.g. Chief Executive",
    // tiltes and subtitles
    title_edit: "Edit the customer",
    title_create: "Create a new customer",
    subtitle: "Fill the inputs to create or edit the customer",
    title_representative: "Representative",
    subtitle_representative: "Fill the inputs with representative data",
    title_addresses: "Addresses",
    subtitle_addresses: "Fill the inputs with the address data",
    // messages
    no_delete_address: "Do not delete all addresses",
  },
  dashboard: {
    dashboard: "Dashboard",
    stats_inflows_title: "Inflows",
    stats_inflows_description: "Total inflows already received",
    stats_inflows_receive_title: "Receivable inflows",
    stats_inflows_receive_description: "Total inflows yet to be received",
    stats_inflows_late_title: "Overdue inflows",
    stats_inflows_late_description:
      "Total inflows that should have already been received",
    stats_outflows_title: "Outflows",
    stats_outflows_description: "Total outflows already made",
    stats_outflows_receive_title: "Pending outflows",
    stats_outflows_receive_description: "Total outflows yet to be made",
    stats_outflows_late_title: "Overdue outflows",
    stats_outflows_late_description:
      "Total outflows that should have already been made",
    chart_inflows_title: "Financial Inflows",
    chart_inflows_description:
      "Inflows distributed over the selected time range.",
    chart_outflows_title: "Financial Outflows",
    chart_outflows_description:
      "Outflows distributed over the selected time range.",
    chart_inflows_resume_title: "Inflows Summary",
    chart_inflows_resume_description: "View of pending and overdue inflows.",
    chart_outflows_resume_title: "Outflows Summary",
    chart_outflows_resume_description: "View of pending and overdue outflows.",
  },
  dialog: {
    title_delete: "Delete",
    description_delete: "Do you want delete delete this item?",
    title_workspace: "Select the workspace",
    title_share: "Share",
    description_share: "Share the item with others using the buttons below:",
    title_close: "Close",
    description_close: "Do you really want close this item?",
  },
  document: {
    placeholder: "Type here the document content...",
    document: "Document",
    documents: "Documents",
    new: "New document",
    type: "Tipo",
    is_public: "Is public?",
    name: "Document name",
    name_placeholder: "e.g. My first document",
    ai_text: "AI text",
    ai_correct: "AI correct",
    documents_size: "Size",
    documents_type: "Type",
    documents_total_title: "Total",
    documents_total_description:
      "Total number of documents that have been saved in this system",
    documents_relation_title: "Relations",
    documents_relation_description:
      "Total number of relations made between the documents and other system modules",
    relations: "relations",
    information: "Information",
    quantity: "Quantity",
    public: "Public",
    private: "Private",
    document_private: "This document is private",
    not_public: "This document is not public",
    recycle_bin: "Recycle bin",
    open_recycle_bin: "Open recycle bin",
  },
  integration: {
    integration: "Integration",
    integrations: "Integrations",
    mailersend: "MailerSend",
    mailersend_description: "Integration to send multiple emails.",
    twilio: "Twilio",
    twilio_description: "Integration to shooting SMS Marketing.",
    stripe: "Stripe",
    stripe_description: "Integration to generate order payments.",
    openai: "OpenAI",
    openai_description:
      "Integration to use OpenAI Artificial Intelligence service.",
    mailchimp: "Mailchimp",
    mailchimp_description: "Integration to send multiples marketing emails.",
    paypal: "PayPal",
    paypal_description: "Integration to manager money and payments.",
    gemini: "Gemini",
    gemini_description:
      "Integration to use Google Artificial Intelligence service.",
    mercadolibre: "Mercado Libre",
    mercadolibre_description: "Integration to sales products.",
    sales: "Sales",
    comunications: "Comunications",
    payments: "Payments",
    ai: "Artificial Intelligence",
    setup: "Setup",
    wip: "Work in progress",
    beta: "In beta",
  },
  login: {
    login: "Log In",
    instance: "Instance",
    username: "Username",
    password: "Password",
    forgot_password: "Forgot the password",
  },
  menu: {
    financial: "Financial",
    dashboard: "Dashboard",
    orders: "Orders",
    inflows: "Inflows",
    outflows: "Outflows",
    recurrences: "Recurrences",
    statements: "Statements",
    administrative: "Administrative",
    customers: "Customers",
    suppliers: "Suppliers",
    users: "Users",
    operational: "Operational",
    products: "Products",
    sales: "Sales",
    services: "Services",
    vehicles: "Vehicles",
    tools: "Tools",
    automations: "Automation",
    documents: "Documents",
    schedules: "Schedules",
    workspaces: "Workspaces",
    integrations: "Integrations",
    accounts: "Banks Accounts",
    settings: "Settings",
    about: "About",
    logout: "Log out",
  },
  order: {
    order: "Order",
    orders: "Orders",
    new: "New order",
    title_edit: "Edit the order",
    title_create: "Create a new order",
    subtitle: "Fill the below fields to create or edit the order",
    title_document: "Document of order",
    subtitle_document: "Select the documents to attach with the order",
    services: "Services",
    title_addresses: "Addresses of order",
    subtitle_addresses: "Put here all addresses relantion with this order",
    title_transport: "Order transport",
    subtitle_transport: "Fill with data relation of order service transport",
    // stages
    draft: "Draft",
    open: "Open",
    pending: "Pending",
    review: "Review",
    progress: "Progress",
    completed: "Completed",
    canceled: "Canceled",
    // filters
    all_stages: "All stages",
    all_users: "All users",
    all_providers: "All providers",
    // list
    id: "Identification",
    stage: "Stage",
    customer: "Customer",
    service_name: "Service name",
    details: "Details",
    empty_details: "Empty details",
    account: "Account",
    addition: "Addition",
    deduction: "Deduction",
    user: "Responsable",
    provider: "Provider",
    addresses: "Addresses",
    // inspect
    date_start: "Start date",
    date_estimated: "Estimated date",
    date_end: "End date",
    no_services: "No services",
    no_details: "No details",
    some_invalid_detail: "Some invalid details",
    description_placeholder: "Type here a brief description about this order",
    quantity: "Quantity",
    quantity_placeholder: "e.g. 2 quantity",
    price: "Price",
    method: "Method",
    vehicle: "Vehicle",
    driver: "Driver",
    // details
    details_title: "Details name",
    details_title_placeholder: "e.g. Fees, Taxs",
    details_type: "Detail type",
    details_mode: "Detail mode",
    details_amount: "Amount",
    details_percent: "Percent",
    tax: "Tax",
    discount: "Discount",
    promo: "Promo",
    coupon: "Coupon",
    voucher: "Voucher",
    fee: "Fee",
    amount: "Amount",
    percent: "Percent",
    // documents
    open_quotation: "Open quotation",
    document_quotation: "Quotation document",
    open_contract: "Open contract",
    document_contract: "Contract document",
  },
  product: {
    product: "Product",
    products: "Products",
    new: "New product",
    no_delete_all_variants: "It is not possible delete all variants",
    physical: "Physical",
    digital: "Digital",
    name: "Product name",
    name_placeholder: "e.g. Tshirt white",
    description_placeholder: "e.g. The brief description about the product...",
    type: "Type",
    category: "Category",
    single: "Single",
    variant: "Variant",
    variants: "Variants",
    photo: "Photo",
    price: "Price",
    title_edit: "Edit the product",
    title_create: "Create a new product",
    subtitle: "Fill the below fields to create or edit the product",
    title_variants: "Variant product",
    subtitle_variants: "Fill the inputs with the variantions of products",
    id: "Id",
    variant_name: "Variant name",
    variant_name_placeholder: "e.g. Tshirt White L (Large)",
    title_specifications: "Specifications",
    subtitle_specifications:
      "If the product has some specifications available digitally or online",
    specific_author: "Author",
    specific_publisher: "Publisher",
    specific_format: "Format",
    specific_size: "Size",
    specific_url: "URL Address",
    specific_version: "Version",
    specific_license: "License",
    lifetime: "Lifetime",
    subscription: "Subscription",
    single_use: "Single use",
    specific_access: "Access",
    download: "Download",
    streaming: "Streaming",
    cloud: "Cloud",
    external: "External",
    specific_method: "Method",
    website: "Website",
    email: "Email",
    service: "Service",
    property_brand: "Brand",
    property_model: "Model",
    property_year: "Year",
    property_color: "Color",
    property_series: "Series",
    property_origin: "Origin",
    property_warranty: "Warranty",
    property_material: "Material",
    specific_condition: "Condition",
    condition_new: "New",
    condition_used: "Used",
    title_properties: "Properties",
    subtitle_properties:
      "If the product has several properties available physicals",
    attribute_weight: "Weight",
    attribute_height: "Height",
    attribute_length: "Length",
    attribute_depth: "Depth",
    attribute_capacity: "Capacity",
    attribute_volume: "Volume",
    title_attributes: "Attributes",
    subtitle_attributes:
      "If the product has attributes to shipping or receiving",
  },
  pages: {
    error: "Error",
    error_description: "An error occurred while accessing this page",
    not_found: "Not Found",
    not_found_description: "The page you accessed was not found",
  },
  sale: {
    sale: "Sale",
    sales: "Sales",
    new: "New sale",
    stage: "Stage",
    all_stage: "All stages",
    id: "Identification",
    customer: "Customer",
    user: "Responsable",
    seller: "Seller",
    all_seller: "All seller",
    account: "Bank account",
    description_placeholder: "Fill here description about the sale...",
    addition: "Addition",
    deduction: "Deduction",
    subtotal: "Subtotal",
    title_edit: "Edit the sale",
    title_create: "Create a new sale",
    subtitle: "Fill the data bellow to edit or create a sale",
    title_stage: "Stages of sale",
    subtitle_stage: "Fill the dates of stages this sale",
    title_address: "Logistics of sale",
    subtitle_address: "Fill with address information of this sale",
    title_document: "Document of sale",
    subtitle_document:
      "Select the document to proporsal and contract of this sale",
    // stages
    funnel: "Funnel stages",
    closing: "Closing stages",
    draft: "Draft",
    open: "Open",
    pending: "Pending",
    paid: "Paid",
    proposal: "Proposal",
    negotiation: "Negotiation",
    won: "Won",
    lost: "Lost",
    processing: "Processing",
    shipped: "Shipped",
    completed: "Completed",
    canceled: "Canceled",
    failed: "Failed",
    refunded: "Refunded",
    returned: "Returned",
    disputed: "Disputed",
    // product
    product_name: "Product name",
    variant_name: "Variant name",
    price: "Price",
    quantity: "Quantity",
    quantity_placeholder: "e.g. 2 products",
    no_products: "No products added",
    // details
    details: "Details",
    details_type: "Type",
    details_mode: "Mode",
    details_amount: "Amount",
    details_percent: "Percent",
    details_title: "Title details",
    details_title_placeholder: "e.g Buy tax",
    empty_details: "Empty details",
    some_invalid_detail: "Has some details with invalid value",
    no_details: "No details added",
    tax: "Tax",
    discount: "Discount",
    promo: "Promo",
    coupon: "Coupon",
    voucher: "Voucher",
    fee: "Fee",
    percent: "Percent",
    amount: "Amount",
    // dates
    date_won: "Won stage date",
    date_lost: "Lost stage date",
    // shipping
    shipping: "Shipping",
    shipping_method: "Shipping method",
    shipping_cost: "Shipping cost",
    shipping_description: "Shipping description",
    shipping_description_placeholder: "e.g. shipped by Express SA",
    shipping_from_postal: "Sender postal code",
    shipping_from_address: "Sender address",
    shipping_to_postal: "Recipient postal code",
    shipping_to_address: "Recipient address",
    standard: "Standard",
    express: "Express",
    pickup_store: "Pickup in store",
    pickup_partner: "Pickup by partner",
    freight: "Freight",
    dropshipping: "Dropshipping",
    delivery: "Delivery",
    // documents
    document_proposal: "Proposal document",
    document_contract: "Contract document",
    open_proposal: "Open proposal",
    open_contract: "Open contract",
  },
  schedule: {
    schedule: "Schedule",
    schedules: "Schedules",
    all_day: "All day",
    previous: "Previous",
    next: "Next",
    today: "Today",
    month: "Month",
    week: "Week",
    day: "Day",
    agenda: "Agenda",
    date: "Date",
    time: "Time",
    event: "Event",
    no_events_in_range: "No events in range.",
    title: "Title",
    no_title: "No title",
    title_placeholder: "e.g. Morning meeting ",
    description: "Description",
    no_description: "No description",
    description_placeholder:
      "e.g. A meeting that will take place on the morning of...",
    category: "Category",
    task: "Task",
    note: "Note",
    remind: "Remind",
    deadline: "Deadline",
    work: "Work",
    reserved: "Reserved",
    meeting: "Meeting",
    priority: "Priority",
    none: "None",
    low: "Low",
    medium: "Medium",
    high: "High",
    critical: "Critical",
    start_date: "Start date",
    end_date: "End date",
    more: "more",
  },
  service: {
    service: "Service",
    services: "Services",
    new: "New service",
    physical: "Physical",
    digital: "Digital",
    type: "Type",
    pricing_method: "Charge for",
    hourly: "Hourly",
    daily: "Daily",
    weekly: "Weekly",
    monthly: "Monthly",
    one_time: "One time",
    per_delivery: "Per delivery",
    name: "Service name",
    name_placeholder: "e.g. Installation of metal structure",
    pricing_value: "Price",
    title_edit: "Edit the service",
    title_create: "Create a new service",
    subtitle: "Fill the below fields to create or edit the service",
    description_placeholder: "Describe the process of this service...",
  },
  settings: {
    settings: "Settings",
    title_preferences: "Preferences",
    subtitle_preferences:
      "Fill the below fields to edit the instance preferences",
    title_apparence: "Apparence",
    subtitle_apparence: "Fill the below fields to edit the instance apparence",
    title_company: "Company",
    subtitle_company: "Fill the below fields to edit the company data",
    title_address: "Address",
    subtitle_address: "Fill the below fields to edit the address data",
    company_name: "Company Name",
    company_name_placeholder: "e.g. John Doe SA",
    company_mobile: "Mobile",
    company_phone: "Phone",
    company_phone_placeholder: "+55 (11) 98888-7777",
    company_email: "Email",
    company_email_placeholder: "e.g. johndoe@mail.com",
    company_website: "Website",
    company_website_placeholder: "https://",
    company_activity: "Atividade",
    logo: "Logo",
    logoLarge: "Logo large",
    favicon: "Favicon",
    color_primary: "Color primary",
    color_secondary: "Color secondary",
    // options
    industry: "Industry",
    commerce: "Commerce",
    services: "Services",
    agribusiness: "Agribusiness",
    construction: "Construction",
    logistics_and_transportation: "Logistics and Transportation",
    education: "Education",
    healthcare: "Healthcare",
    it_and_software: "IT and Software",
    financial_services: "Financial Services",
    advertising_and_communication: "Advertising and Communication",
    public_sector: "Public Sector",
    non_profits_and_foundations: "Non-profits and Foundations",
    import_and_export: "Import and Export",
    energy_and_utilities: "Energy and Utilities",
    mining_and_extraction: "Mining and Extraction",
  },
  supplier: {
    // list
    supplier: "Supplier",
    suppliers: "Suppliers",
    new: "New supplier",
    // inputs
    name: "Supplier name",
    document_1: "Document 1",
    mobile: "Mobile",
    phone_1: "Phone 1",
    email: "Email",
    description: "Description",
    representative_name: "Representative name",
    representative_role: "Representative role",
    phone_2: "Phone 2",
    document_2: "Document 2",
    address: "Address",
    // placeholders
    name_placeholder: "e.g. John Doe Inc",
    document_1_placeholder: "123.456.789-10",
    mobile_placeholder: "+1 (123) 4567-890",
    phone_placeholder: "+1 (123) 4567-890",
    email_placeholder: "e.g. johndoe@email.com",
    description_placeholder: "Type here a brief description about the supplier",
    representative_name_placeholder: "e.g. John Doe",
    representative_role_placeholder: "e.g. Chief Executive",
    document_2_placeholder: "e.g. 111.222.33-44",
    // titles and subtitles
    title_edit: "Edit the supplier ",
    title_create: "Create a new supplier",
    subtitle: "Fill the inputs to edit or create the supplier",
    title_addresses: "Addresses",
    subtitle_addresses: "Fill the inputs with address data",
    title_representative: "Representative",
    subtitle_representative: "Fill the inputs with representative data",
    // messages
    no_delete_address: "Do not delete all addresses",
  },
  stacks: {
    // no
    no_name: "No name",
    no_action: "No ação found",
    no_entity: "No module found",
    no_email: "No email",
    no_phone: "No phone",
    no_document: "No document",
    no_find_item: "The item was not found",
    no_option: "No options selected",
    no_description: "No description",
    no_items: "No items found",
    no_instance: "No instance found",
    no_token: "No token found",
    no_user: "No user data found",
    no_workspace: "No workspaces found",
    no_integration: "No integration found",
    session_expired: "Your sessions is expired",
    no_address: "No address",
    // limit
    limit_workspace: "Workspace limit reached",
    limit_user: "User limit reached",
    wrong_file_format: "The file has the wrong format",
    limit_image_5mb: "The image file exceeds the 5MB limit",
    // fields
    invalid_enum_value: "Unknown value",
    wrong_credentials: "Wrong credentials",
    incorrect_length: "Incorrect length",
    too_big: "Too big",
    invalid_string: "Invalid string",
    invalid_type: "Invalid type",
    not_finite: "Not finite",
    too_small: "Too small",
    invalid_phone_number: "Invalid phone number",
    invalid_document: "Invalid document",
    invalid_date: "Invalid date",
    invalid_id: "Invalid Id",
    invalid_postal_code: "Invalid postal code",
  },
  toast: {
    // title
    success: "Success!",
    warning_error: "Oops!",
    loading: "Loading...",
    // success
    success_restore: "The item was restored.",
    success_find: "The item was found.",
    success_download: "The item has been downloaded.",
    success_copy: "The id was copied.",
    success_login: "You have been logged in.",
    success_create: "The item was created.",
    success_edit: "The item was edited.",
    success_delete: "The item was deleted.",
    success_workspace: "The workspace was selected.",
    // warning
    warning_restore: "Item not restored.",
    warning_find: "Item not found.",
    warning_create: "The item was not created.",
    warning_edit: "The item not been edited.",
    warning_delete: "The item was not deleted.",
    warning_copy: "The id was not copied.",
    // error
    error_restore: "An error ocurred while restored the item.",
    error_create: "An error occurred while creating the item.",
    error_edit: "An error occurred while editing the item.",
    error_delete: "An error occurred while deleting the item.",
  },
  user: {
    user: "User",
    users: "Users",
    new: "New user",
    title_edit: "Edit the user",
    title_create: "Create a new user",
    subtitle: "Fill the below fields to create or edit the user",
    role: "Role",
    photo: "Photo",
    name: "User name",
    name_placeholder: "e.g. John Doe",
    document: "Document",
    mobile: "Mobile",
    email: "Email",
    address: "Address",
    document_1: "Document 1",
    document_2: "Document 2",
    document_placeholder: "123.456.789-10",
    phone: "Phone number",
    phone_placeholder: "+1 (123) 234-5678",
    email_placeholder: "e.g. johndoe@company.com",
    title_audit: "Audit",
    subtitle_audit: "See all logs of user actions",
    title_address: "User address",
    subtitle_address: "Fill the inputs with the address data from user",
    schedules_title: "Schedules",
    schedules_description:
      "All schedules that reservade in schedule list in this user",
    not_change_status: "It is not allowed to deactivate the user himself",
    // audit
    insert: "Created",
    create: "Created",
    read: "Read",
    update: "Updated",
    delete: "Deleted",
    to_audit: "To audit",
    audit: "Audit",
    user_id: "Responsable",
    action: "Action",
    entity: "Module",
    snapshot_name: "Name",
    workspace: "Workspace",
  },
  vehicle: {
    vehicle: "Vehicle",
    vehicles: "Vehicles",
    new: "New vehicle",
    category: "Category",
    motocycle: "Motocycle",
    pickup: "Pickup",
    truck: "Truck",
    passenger: "Passenger",
    commercial: "Commercial",
    cargo_light: "Light cargo",
    cargo: "Cargo",
    cargo_heavy: "Heavy cargo",
    transport: "Transport",
    vintage: "Vintage",
    competition: "Competition",
    polylift_single: "Polilift single",
    polylift_double: "Polilift double",
    hydro_vacuum: "Hydrovacuum",
    rollon_rolloff: "Rollon and Rolloff",
    bus: "Bus",
    tractor: "Tractor",
    trailer: "Trailer",
    tricycle: "Tricycle",
    quadricycle: "Quadricycle",
    buggy: "Buggy",
    special: "Special",
    others: "Others",
    utility: "Utility",
    name: "Vehicle name",
    name_placeholder: "e.g. Ford Mustang",
    description_placeholder: "Type here all details about the vehicle...",
    plate: "Plate",
    plate_brazil: "Plate Brazil",
    plate_mercosul: "Plate Mercosul",
    plate_type: "Plate type",
    plate_brazil_placeholder: "ABC-1234",
    plate_mercosul_placeholder: "ABC1D34",
    brand: "Brand",
    brand_placeholder: "e.g. Ford",
    model: "Model",
    model_placeholder: "e.g. Mustang",
    title_edit: "Edit the vehicle",
    title_create: "Create a new vehicle",
    subtitle: "Fill the below fields to create or edit the vehicle",
    chassi: "Chassi serial",
    color: "Main color",
    year: "Year",
    document: "Document (ID Vehicle)",
    document_placeholder: "1234567890",
    maintenance: "Maintenance",
    refuel: "Refuel",
    no_brand: "No brand",
    no_model: "No model",
  },
  workspace: {
    workspaces: "Workspaces",
    new: "New workspace",
    name: "Workspace Name",
    name_placeholder: "e.g. Head Office",
    title_edit: "Edit the workspace",
    title_create: "Create a new workspace",
    subtitle: "Fill the below fields to create or edit the workspaces",
    description_placeholder: "A brief description about the workspace",
    units: "Units",
    teams: "Teams",
    offices: "Offices",
    centers: "Centers",
    agencies: "Agencies",
    branches: "Branches",
    sections: "Sections",
    divisions: "Divisions",
    operations: "Operations",
    departments: "Departments",
    subsidiaries: "Subdidiaries",
    not_change_status: "Not allowed disabled selected workspace",
    not_delete: "Not allowed delete selected workspace",
    already_selected_workspace: "This workspace already selected!",
  },
};

const Translate = {
  pt: TranslatePt,
  en: TranslateEn,
};

export default Translate;
