export const VehicleCategoryOptions = [
  "passenger",
  "motocycle",
  "pickup",
  "truck",
  "commercial",
  "cargo_light",
  "cargo_heavy",
  "transport",
  "cargo",
  "vintage",
  "competition",
  "polylift_single",
  "polylift_double",
  "hydro_vacuum",
  "rollon_rolloff",
  "bus",
  "tractor",
  "trailer",
  "tricycle",
  "quadricycle",
  "buggy",
  "utility",
  "special",
  "others",
];

export const VehicleBrandsOptions = [
  { name: "acura", image: "/brands/acura.png" },
  { name: "alfa", image: "/brands/alfa romeo.png" },
  { name: "alpina", image: "/brands/alpina.svg" },
  { name: "aston", image: "/brands/aston martin.png" },
  { name: "audi", image: "/brands/audi.png" },
  { name: "bentley", image: "/brands/bentley.png" },
  { name: "bmw", image: "/brands/bmw.png" },
  { name: "bugatti", image: "/brands/bugatti.jpg" },
  { name: "buick", image: "/brands/buick.jpeg" },
  { name: "byd", image: "/brands/byd.png" },
  { name: "cadillac", image: "/brands/cadillac.jpeg" },
  { name: "chevrolet", image: "/brands/chevrolet.jpeg" },
  { name: "chrysler", image: "/brands/chrysler.png" },
  { name: "citroen", image: "/brands/citroen.png" },
  { name: "daf", image: "/brands/daf.svg" },
  { name: "dodge", image: "/brands/dodge.png" },
  { name: "ferrari", image: "/brands/ferrari.png" },
  { name: "fiat", image: "/brands/fiat.jpeg" },
  { name: "ford", image: "/brands/ford.png" },
  { name: "geely", image: "/brands/geely.png" },
  { name: "gmc", image: "/brands/gmc.png" },
  { name: "gwm", image: "/brands/gwm.svg" },
  { name: "honda", image: "/brands/honda.svg" },
  { name: "hyundai", image: "/brands/hyundai.png" },
  { name: "iveco", image: "/brands/iveco.svg" },
  { name: "jac", image: "/brands/jac.jpg" },
  { name: "jaguar", image: "/brands/jaguar.png" },
  { name: "jeep", image: "/brands/jeep.png" },
  { name: "kenworth", image: "/brands/kenworth.webp" },
  { name: "kia", image: "/brands/kia.png" },
  { name: "lamborghini", image: "/brands/lamborghini.jpeg" },
  { name: "land", image: "/brands/land rover.png" },
  { name: "lexus", image: "/brands/lexus.jpeg" },
  { name: "lotus", image: "/brands/lotus.png" },
  { name: "man", image: "/brands/man.png" },
  { name: "maserati", image: "/brands/maserati.png" },
  { name: "maybach", image: "/brands/maybach.png" },
  { name: "mazda", image: "/brands/mazda.png" },
  { name: "mercedes_benz", image: "/brands/mercedes_benz.png" },
  { name: "mini", image: "/brands/mini.png" },
  { name: "mitsubishi", image: "/brands/mitsubishi.svg" },
  { name: "nissan", image: "/brands/nissan.png" },
  { name: "ora", image: "/brands/ora.png" },
  { name: "peterbilt", image: "/brands/peterbilt.svg" },
  { name: "peugeot", image: "/brands/peugeot.jpeg" },
  { name: "porsche", image: "/brands/porsche.png" },
  { name: "ram", image: "/brands/ram.jpeg" },
  { name: "renault", image: "/brands/renault.jpg" },
  { name: "rolls_royce", image: "/brands/rolls_royce.webp" },
  { name: "scania", image: "/brands/scania.webp" },
  { name: "seat", image: "/brands/seat.png" },
  { name: "skoda", image: "/brands/skoda.jpeg" },
  { name: "smart", image: "/brands/smart.png" },
  { name: "subaru", image: "/brands/subaru.jpeg" },
  { name: "suzuki", image: "/brands/suzuki.png" },
  { name: "tesla", image: "/brands/tesla.png" },
  { name: "toyota", image: "/brands/toyota.jpg" },
  { name: "volkswagen", image: "/brands/volkswagen.png" },
  { name: "volvo", image: "/brands/volvo.png" },
];

export const VehicleGasStationOptions = [
  { name: "ALE", image: "/gas_stations/ale.jpeg" },
  { name: "Assaí", image: "/gas_stations/assai.png" },
  { name: "Atacadão", image: "/gas_stations/atacadao.png" },
  { name: "Atem", image: "/gas_stations/atem.png" },
  { name: "Carrefour", image: "/gas_stations/carrefour.png" },
  { name: "Charrua", image: "/gas_stations/charrua.png" },
  { name: "ESSO", image: "/gas_stations/esso.png" },
  { name: "Graal", image: "/gas_stations/graal.jpg" },
  { name: "Ipiranga", image: "/gas_stations/ipiranga.jpg" },
  { name: "Larco", image: "/gas_stations/larco.jpeg" },
  { name: "Petrobras", image: "/gas_stations/petrobras.png" },
  { name: "Petronas", image: "/gas_stations/petronas.jpeg" },
  { name: "Rede7", image: "/gas_stations/rede7.png" },
  { name: "Repsol", image: "/gas_stations/repsol.jpg" },
  { name: "Rodoil", image: "/gas_stations/rodoil.webp" },
  { name: "Shell", image: "/gas_stations/shell.png" },
  { name: "Texaco", image: "/gas_stations/texaco.webp" },
  { name: "TotalEnergy", image: "/gas_stations/totalenergy.png" },
  { name: "Vibra", image: "/gas_stations/vibra.jpeg" },
];
